// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxcometbft/clob/order.proto

package clob

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	subaccounts "github.com/KYVENetwork/dydx-cometbft/proto/dydxcometbft/subaccounts"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Represents the side of the orderbook the order will be placed on.
// Note that Side.SIDE_UNSPECIFIED is an invalid order and cannot be
// placed on the orderbook.
type Order_Side int32

const (
	// Default value. This value is invalid and unused.
	Order_SIDE_UNSPECIFIED Order_Side = 0
	// SIDE_BUY is used to represent a BUY order.
	Order_SIDE_BUY Order_Side = 1
	// SIDE_SELL is used to represent a SELL order.
	Order_SIDE_SELL Order_Side = 2
)

var Order_Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "SIDE_BUY",
	2: "SIDE_SELL",
}

var Order_Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"SIDE_BUY":         1,
	"SIDE_SELL":        2,
}

func (x Order_Side) String() string {
	return proto.EnumName(Order_Side_name, int32(x))
}

func (Order_Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{6, 0}
}

// TimeInForce indicates how long an order will remain active before it
// is executed or expires.
type Order_TimeInForce int32

const (
	// TIME_IN_FORCE_UNSPECIFIED represents the default behavior where an
	// order will first match with existing orders on the book, and any
	// remaining size will be added to the book as a maker order.
	Order_TIME_IN_FORCE_UNSPECIFIED Order_TimeInForce = 0
	// TIME_IN_FORCE_IOC enforces that an order only be matched with
	// maker orders on the book. If the order has remaining size after
	// matching with existing orders on the book, the remaining size
	// is not placed on the book.
	Order_TIME_IN_FORCE_IOC Order_TimeInForce = 1
	// TIME_IN_FORCE_POST_ONLY enforces that an order only be placed
	// on the book as a maker order. Note this means that validators will cancel
	// any newly-placed post only orders that would cross with other maker
	// orders.
	Order_TIME_IN_FORCE_POST_ONLY Order_TimeInForce = 2
	// TIME_IN_FORCE_FILL_OR_KILL enforces that an order will either be filled
	// completely and immediately by maker orders on the book or canceled if the
	// entire amount can‘t be matched.
	Order_TIME_IN_FORCE_FILL_OR_KILL Order_TimeInForce = 3
)

var Order_TimeInForce_name = map[int32]string{
	0: "TIME_IN_FORCE_UNSPECIFIED",
	1: "TIME_IN_FORCE_IOC",
	2: "TIME_IN_FORCE_POST_ONLY",
	3: "TIME_IN_FORCE_FILL_OR_KILL",
}

var Order_TimeInForce_value = map[string]int32{
	"TIME_IN_FORCE_UNSPECIFIED":  0,
	"TIME_IN_FORCE_IOC":          1,
	"TIME_IN_FORCE_POST_ONLY":    2,
	"TIME_IN_FORCE_FILL_OR_KILL": 3,
}

func (x Order_TimeInForce) String() string {
	return proto.EnumName(Order_TimeInForce_name, int32(x))
}

func (Order_TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{6, 1}
}

// OrderId refers to a single order belonging to a Subaccount.
type OrderId struct {
	// The subaccount ID that opened this order.
	// Note that this field has `gogoproto.nullable = false` so that it is
	// generated as a value instead of a pointer. This is because the `OrderId`
	// proto is used as a key within maps, and map comparisons will compare
	// pointers for equality (when the desired behavior is to compare the values).
	SubaccountId subaccounts.SubaccountId `protobuf:"bytes,1,opt,name=subaccount_id,json=subaccountId,proto3" json:"subaccount_id"`
	// The client ID of this order, unique with respect to the specific
	// sub account (I.E., the same subaccount can't have two orders with
	// the same ClientId).
	ClientId uint32 `protobuf:"fixed32,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// order_flags represent order flags for the order. This field is invalid if
	// it's greater than 127 (larger than one byte). Each bit in the first byte
	// represents a different flag. Currently only two flags are supported.
	//
	// Starting from the bit after the most MSB (note that the MSB is used in
	// proto varint encoding, and therefore cannot be used): Bit 1 is set if this
	// order is a Long-Term order (0x40, or 64 as a uint8). Bit 2 is set if this
	// order is a Conditional order (0x20, or 32 as a uint8).
	//
	// If neither bit is set, the order is assumed to be a Short-Term order.
	//
	// If both bits are set or bits other than the 2nd and 3rd are set, the order
	// ID is invalid.
	OrderFlags uint32 `protobuf:"varint,3,opt,name=order_flags,json=orderFlags,proto3" json:"order_flags,omitempty"`
	// ID of the CLOB the order is created for.
	ClobPairId uint32 `protobuf:"varint,4,opt,name=clob_pair_id,json=clobPairId,proto3" json:"clob_pair_id,omitempty"`
}

func (m *OrderId) Reset()         { *m = OrderId{} }
func (m *OrderId) String() string { return proto.CompactTextString(m) }
func (*OrderId) ProtoMessage()    {}
func (*OrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{0}
}
func (m *OrderId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderId.Merge(m, src)
}
func (m *OrderId) XXX_Size() int {
	return m.Size()
}
func (m *OrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderId.DiscardUnknown(m)
}

var xxx_messageInfo_OrderId proto.InternalMessageInfo

func (m *OrderId) GetSubaccountId() subaccounts.SubaccountId {
	if m != nil {
		return m.SubaccountId
	}
	return subaccounts.SubaccountId{}
}

func (m *OrderId) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *OrderId) GetOrderFlags() uint32 {
	if m != nil {
		return m.OrderFlags
	}
	return 0
}

func (m *OrderId) GetClobPairId() uint32 {
	if m != nil {
		return m.ClobPairId
	}
	return 0
}

// OrdersFilledDuringLatestBlock represents a list of `OrderIds` that were
// filled by any non-zero amount in the latest block.
type OrdersFilledDuringLatestBlock struct {
	// A list of unique order_ids that were filled by any non-zero amount in the
	// latest block.
	OrderIds []OrderId `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids"`
}

func (m *OrdersFilledDuringLatestBlock) Reset()         { *m = OrdersFilledDuringLatestBlock{} }
func (m *OrdersFilledDuringLatestBlock) String() string { return proto.CompactTextString(m) }
func (*OrdersFilledDuringLatestBlock) ProtoMessage()    {}
func (*OrdersFilledDuringLatestBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{1}
}
func (m *OrdersFilledDuringLatestBlock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrdersFilledDuringLatestBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrdersFilledDuringLatestBlock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrdersFilledDuringLatestBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdersFilledDuringLatestBlock.Merge(m, src)
}
func (m *OrdersFilledDuringLatestBlock) XXX_Size() int {
	return m.Size()
}
func (m *OrdersFilledDuringLatestBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdersFilledDuringLatestBlock.DiscardUnknown(m)
}

var xxx_messageInfo_OrdersFilledDuringLatestBlock proto.InternalMessageInfo

func (m *OrdersFilledDuringLatestBlock) GetOrderIds() []OrderId {
	if m != nil {
		return m.OrderIds
	}
	return nil
}

// PotentiallyPrunableOrders represents a list of orders that may be prunable
// from state at a future block height.
type PotentiallyPrunableOrders struct {
	// A list of unique order_ids that may potentially be pruned from state at a
	// future block height.
	OrderIds []OrderId `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids"`
}

func (m *PotentiallyPrunableOrders) Reset()         { *m = PotentiallyPrunableOrders{} }
func (m *PotentiallyPrunableOrders) String() string { return proto.CompactTextString(m) }
func (*PotentiallyPrunableOrders) ProtoMessage()    {}
func (*PotentiallyPrunableOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{2}
}
func (m *PotentiallyPrunableOrders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PotentiallyPrunableOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PotentiallyPrunableOrders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PotentiallyPrunableOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotentiallyPrunableOrders.Merge(m, src)
}
func (m *PotentiallyPrunableOrders) XXX_Size() int {
	return m.Size()
}
func (m *PotentiallyPrunableOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_PotentiallyPrunableOrders.DiscardUnknown(m)
}

var xxx_messageInfo_PotentiallyPrunableOrders proto.InternalMessageInfo

func (m *PotentiallyPrunableOrders) GetOrderIds() []OrderId {
	if m != nil {
		return m.OrderIds
	}
	return nil
}

// OrderFillState represents the fill amount of an order according to on-chain
// state. This proto includes both the current on-chain fill amount of the
// order, as well as the block at which this information can be pruned from
// state.
type OrderFillState struct {
	// The current fillAmount of the order according to on-chain state.
	FillAmount uint64 `protobuf:"varint,1,opt,name=fill_amount,json=fillAmount,proto3" json:"fill_amount,omitempty"`
	// The block height at which the fillAmount state for this order can be
	// pruned.
	PrunableBlockHeight uint32 `protobuf:"varint,2,opt,name=prunable_block_height,json=prunableBlockHeight,proto3" json:"prunable_block_height,omitempty"`
}

func (m *OrderFillState) Reset()         { *m = OrderFillState{} }
func (m *OrderFillState) String() string { return proto.CompactTextString(m) }
func (*OrderFillState) ProtoMessage()    {}
func (*OrderFillState) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{3}
}
func (m *OrderFillState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderFillState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderFillState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderFillState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFillState.Merge(m, src)
}
func (m *OrderFillState) XXX_Size() int {
	return m.Size()
}
func (m *OrderFillState) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFillState.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFillState proto.InternalMessageInfo

func (m *OrderFillState) GetFillAmount() uint64 {
	if m != nil {
		return m.FillAmount
	}
	return 0
}

func (m *OrderFillState) GetPrunableBlockHeight() uint32 {
	if m != nil {
		return m.PrunableBlockHeight
	}
	return 0
}

// StatefulOrderTimeSliceValue represents the type of the value of the
// `StatefulOrdersTimeSlice` in state. The `StatefulOrdersTimeSlice`
// in state consists of key/value pairs where the keys are UTF-8-encoded
// `RFC3339NANO` timestamp strings with right-padded zeroes and no
// time zone info, and the values are of type `StatefulOrderTimeSliceValue`.
// This `StatefulOrdersTimeSlice` in state is used for managing stateful
// order expiration.
type StatefulOrderTimeSliceValue struct {
	// A unique list of order_ids that expire at this timestamp, sorted in
	// ascending order by block height and transaction index of each stateful
	// order.
	OrderIds []OrderId `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids"`
}

func (m *StatefulOrderTimeSliceValue) Reset()         { *m = StatefulOrderTimeSliceValue{} }
func (m *StatefulOrderTimeSliceValue) String() string { return proto.CompactTextString(m) }
func (*StatefulOrderTimeSliceValue) ProtoMessage()    {}
func (*StatefulOrderTimeSliceValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{4}
}
func (m *StatefulOrderTimeSliceValue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatefulOrderTimeSliceValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatefulOrderTimeSliceValue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatefulOrderTimeSliceValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatefulOrderTimeSliceValue.Merge(m, src)
}
func (m *StatefulOrderTimeSliceValue) XXX_Size() int {
	return m.Size()
}
func (m *StatefulOrderTimeSliceValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StatefulOrderTimeSliceValue.DiscardUnknown(m)
}

var xxx_messageInfo_StatefulOrderTimeSliceValue proto.InternalMessageInfo

func (m *StatefulOrderTimeSliceValue) GetOrderIds() []OrderId {
	if m != nil {
		return m.OrderIds
	}
	return nil
}

// StatefulOrderPlacement represents the placement of a stateful order in
// state. It stores the stateful order itself and the `BlockHeight` and
// `TransactionIndex` at which the order was placed.
type StatefulOrderPlacement struct {
	Order Order `protobuf:"bytes,1,opt,name=order,proto3" json:"order"`
	// The block height at which the order was placed.
	// Used for ordering by time priority when the chain is restarted.
	BlockHeight uint32 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// The index at which this transaction appeared in the
	// `MsgProposedMatchOrders` message. Used for ordering by time priority when
	// the chain is restarted.
	TransactionIndex uint32 `protobuf:"varint,3,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
}

func (m *StatefulOrderPlacement) Reset()         { *m = StatefulOrderPlacement{} }
func (m *StatefulOrderPlacement) String() string { return proto.CompactTextString(m) }
func (*StatefulOrderPlacement) ProtoMessage()    {}
func (*StatefulOrderPlacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{5}
}
func (m *StatefulOrderPlacement) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StatefulOrderPlacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StatefulOrderPlacement.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StatefulOrderPlacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatefulOrderPlacement.Merge(m, src)
}
func (m *StatefulOrderPlacement) XXX_Size() int {
	return m.Size()
}
func (m *StatefulOrderPlacement) XXX_DiscardUnknown() {
	xxx_messageInfo_StatefulOrderPlacement.DiscardUnknown(m)
}

var xxx_messageInfo_StatefulOrderPlacement proto.InternalMessageInfo

func (m *StatefulOrderPlacement) GetOrder() Order {
	if m != nil {
		return m.Order
	}
	return Order{}
}

func (m *StatefulOrderPlacement) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *StatefulOrderPlacement) GetTransactionIndex() uint32 {
	if m != nil {
		return m.TransactionIndex
	}
	return 0
}

// Order represents a single order belonging to a `Subaccount`
// for a particular `ClobPair`.
type Order struct {
	// The unique ID of this order. Meant to be unique across all orders.
	OrderId OrderId    `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id"`
	Side    Order_Side `protobuf:"varint,2,opt,name=side,proto3,enum=dydxcometbft.clob.Order_Side" json:"side,omitempty"`
	// The size of this order in base quantums. Must be a multiple of
	// `ClobPair.StepBaseQuantums` and above `ClobPair.MinOrderBaseQuantums`
	// (where `ClobPair.Id = orderId.ClobPairId`).
	Quantums uint64 `protobuf:"varint,3,opt,name=quantums,proto3" json:"quantums,omitempty"`
	// The price level that this order will be placed at on the orderbook,
	// in subticks. Must be a multiple of ClobPair.SubticksPerTick
	// (where `ClobPair.Id = orderId.ClobPairId`).
	Subticks uint64 `protobuf:"varint,4,opt,name=subticks,proto3" json:"subticks,omitempty"`
	// Information about when the order expires.
	//
	// Types that are valid to be assigned to GoodTilOneof:
	//
	//	*Order_GoodTilBlock
	//	*Order_GoodTilBlockTime
	GoodTilOneof isOrder_GoodTilOneof `protobuf_oneof:"good_til_oneof"`
	// The time in force of this order.
	TimeInForce Order_TimeInForce `protobuf:"varint,7,opt,name=time_in_force,json=timeInForce,proto3,enum=dydxcometbft.clob.Order_TimeInForce" json:"time_in_force,omitempty"`
	// Enforces that the order can only reduce the size of an existing position.
	// If a ReduceOnly order would change the side of the existing position,
	// its size is reduced to that of the remaining size of the position.
	// If existing orders on the book with ReduceOnly
	// would already close the position, the least aggressive (out-of-the-money)
	// ReduceOnly orders are resized and canceled first.
	ReduceOnly bool `protobuf:"varint,8,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	// Set of bit flags set arbitrarily by clients and ignored by the protocol.
	// Used by indexer to infer information about a placed order.
	ClientMetadata uint32 `protobuf:"varint,9,opt,name=client_metadata,json=clientMetadata,proto3" json:"client_metadata,omitempty"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_412b688ef1f07093, []int{6}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Order.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return m.Size()
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

type isOrder_GoodTilOneof interface {
	isOrder_GoodTilOneof()
	MarshalTo([]byte) (int, error)
	Size() int
}

type Order_GoodTilBlock struct {
	GoodTilBlock uint32 `protobuf:"varint,5,opt,name=good_til_block,json=goodTilBlock,proto3,oneof" json:"good_til_block,omitempty"`
}
type Order_GoodTilBlockTime struct {
	GoodTilBlockTime uint32 `protobuf:"fixed32,6,opt,name=good_til_block_time,json=goodTilBlockTime,proto3,oneof" json:"good_til_block_time,omitempty"`
}

func (*Order_GoodTilBlock) isOrder_GoodTilOneof()     {}
func (*Order_GoodTilBlockTime) isOrder_GoodTilOneof() {}

func (m *Order) GetGoodTilOneof() isOrder_GoodTilOneof {
	if m != nil {
		return m.GoodTilOneof
	}
	return nil
}

func (m *Order) GetOrderId() OrderId {
	if m != nil {
		return m.OrderId
	}
	return OrderId{}
}

func (m *Order) GetSide() Order_Side {
	if m != nil {
		return m.Side
	}
	return Order_SIDE_UNSPECIFIED
}

func (m *Order) GetQuantums() uint64 {
	if m != nil {
		return m.Quantums
	}
	return 0
}

func (m *Order) GetSubticks() uint64 {
	if m != nil {
		return m.Subticks
	}
	return 0
}

func (m *Order) GetGoodTilBlock() uint32 {
	if x, ok := m.GetGoodTilOneof().(*Order_GoodTilBlock); ok {
		return x.GoodTilBlock
	}
	return 0
}

func (m *Order) GetGoodTilBlockTime() uint32 {
	if x, ok := m.GetGoodTilOneof().(*Order_GoodTilBlockTime); ok {
		return x.GoodTilBlockTime
	}
	return 0
}

func (m *Order) GetTimeInForce() Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return Order_TIME_IN_FORCE_UNSPECIFIED
}

func (m *Order) GetReduceOnly() bool {
	if m != nil {
		return m.ReduceOnly
	}
	return false
}

func (m *Order) GetClientMetadata() uint32 {
	if m != nil {
		return m.ClientMetadata
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Order) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Order_GoodTilBlock)(nil),
		(*Order_GoodTilBlockTime)(nil),
	}
}

func init() {
	proto.RegisterEnum("dydxcometbft.clob.Order_Side", Order_Side_name, Order_Side_value)
	proto.RegisterEnum("dydxcometbft.clob.Order_TimeInForce", Order_TimeInForce_name, Order_TimeInForce_value)
	proto.RegisterType((*OrderId)(nil), "dydxcometbft.clob.OrderId")
	proto.RegisterType((*OrdersFilledDuringLatestBlock)(nil), "dydxcometbft.clob.OrdersFilledDuringLatestBlock")
	proto.RegisterType((*PotentiallyPrunableOrders)(nil), "dydxcometbft.clob.PotentiallyPrunableOrders")
	proto.RegisterType((*OrderFillState)(nil), "dydxcometbft.clob.OrderFillState")
	proto.RegisterType((*StatefulOrderTimeSliceValue)(nil), "dydxcometbft.clob.StatefulOrderTimeSliceValue")
	proto.RegisterType((*StatefulOrderPlacement)(nil), "dydxcometbft.clob.StatefulOrderPlacement")
	proto.RegisterType((*Order)(nil), "dydxcometbft.clob.Order")
}

func init() { proto.RegisterFile("dydxcometbft/clob/order.proto", fileDescriptor_412b688ef1f07093) }

var fileDescriptor_412b688ef1f07093 = []byte{
	// 814 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x41, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0xdb, 0x74, 0x9b, 0xbe, 0x24, 0xc5, 0x9d, 0xdd, 0x05, 0x6f, 0xaa, 0x66, 0x43, 0x84,
	0x96, 0x20, 0x44, 0x22, 0x0a, 0x17, 0x04, 0x1c, 0x48, 0x9b, 0xa8, 0xd6, 0x66, 0x9b, 0x60, 0x77,
	0x2b, 0x75, 0x85, 0x18, 0x8d, 0x3d, 0x93, 0x74, 0xd4, 0xb1, 0xa7, 0xd8, 0x63, 0xb1, 0xbd, 0xf1,
	0x13, 0xf8, 0x05, 0xfc, 0x12, 0x7e, 0xc0, 0x1e, 0xf7, 0xc8, 0x09, 0xa1, 0xf6, 0xca, 0x8f, 0x40,
	0x33, 0xf6, 0xa6, 0x0e, 0x4b, 0xc5, 0x61, 0x6f, 0xf3, 0xbe, 0xef, 0xf9, 0x7b, 0xef, 0x7b, 0xf3,
	0x6c, 0xc3, 0x1e, 0xbd, 0xa2, 0x2f, 0x43, 0x19, 0x31, 0x15, 0xcc, 0xd5, 0x20, 0x14, 0x32, 0x18,
	0xc8, 0x84, 0xb2, 0xa4, 0x7f, 0x99, 0x48, 0x25, 0xd1, 0x4e, 0x99, 0xee, 0x6b, 0xba, 0xf5, 0x60,
	0x21, 0x17, 0xd2, 0xb0, 0x03, 0x7d, 0xca, 0x13, 0x5b, 0x9f, 0xac, 0xe8, 0xa4, 0x59, 0x40, 0xc2,
	0x50, 0x66, 0xb1, 0x4a, 0x4b, 0xe7, 0x3c, 0xb5, 0xfb, 0xbb, 0x05, 0x9b, 0x53, 0x5d, 0xc3, 0xa5,
	0xe8, 0x7b, 0x68, 0xde, 0xf2, 0x98, 0x53, 0xc7, 0xea, 0x58, 0xbd, 0xfa, 0xfe, 0x93, 0xfe, 0x4a,
	0xdd, 0x92, 0x5c, 0xdf, 0x5f, 0x9e, 0x5d, 0x3a, 0xac, 0xbe, 0xfa, 0xf3, 0x71, 0xc5, 0x6b, 0xa4,
	0x25, 0x0c, 0xed, 0xc2, 0x56, 0x28, 0x38, 0xcb, 0xe5, 0xd6, 0x3a, 0x56, 0x6f, 0xd3, 0xab, 0xe5,
	0x80, 0x4b, 0xd1, 0x63, 0xa8, 0x1b, 0x7b, 0x78, 0x2e, 0xc8, 0x22, 0x75, 0xd6, 0x3b, 0x56, 0xaf,
	0xe9, 0x81, 0x81, 0xc6, 0x1a, 0x41, 0x1d, 0x68, 0x68, 0x97, 0xf8, 0x92, 0xf0, 0x44, 0x0b, 0x54,
	0xf3, 0x0c, 0x8d, 0xcd, 0x08, 0x4f, 0x5c, 0xda, 0xfd, 0x11, 0xf6, 0x4c, 0xf7, 0xe9, 0x98, 0x0b,
	0xc1, 0xe8, 0x61, 0x96, 0xf0, 0x78, 0x31, 0x21, 0x8a, 0xa5, 0x6a, 0x28, 0x64, 0x78, 0x81, 0xbe,
	0x85, 0xad, 0xbc, 0x06, 0xa7, 0xa9, 0x63, 0x75, 0xd6, 0x7b, 0xf5, 0xfd, 0x56, 0xff, 0xad, 0x39,
	0xf6, 0x8b, 0x11, 0x14, 0x1e, 0x6a, 0x32, 0x0f, 0xd3, 0xee, 0x0b, 0x78, 0x34, 0x93, 0x8a, 0xc5,
	0x8a, 0x13, 0x21, 0xae, 0x66, 0x49, 0x16, 0x93, 0x40, 0xb0, 0xbc, 0xe4, 0xbb, 0x6a, 0x33, 0xd8,
	0x36, 0x94, 0x6e, 0xdd, 0x57, 0x44, 0x31, 0x3d, 0x90, 0x39, 0x17, 0x02, 0x93, 0x48, 0x8f, 0xcf,
	0x8c, 0xbf, 0xea, 0x81, 0x86, 0xbe, 0x33, 0x08, 0xda, 0x87, 0x87, 0x97, 0x45, 0x0f, 0x38, 0xd0,
	0xfe, 0xf0, 0x39, 0xe3, 0x8b, 0x73, 0x65, 0x46, 0xdb, 0xf4, 0xee, 0xbf, 0x21, 0x8d, 0xf7, 0x23,
	0x43, 0x75, 0x7f, 0x80, 0x5d, 0xa3, 0x3e, 0xcf, 0x84, 0x29, 0x77, 0xc2, 0x23, 0xe6, 0x0b, 0x1e,
	0xb2, 0x53, 0x22, 0x32, 0xf6, 0xae, 0x26, 0x7e, 0xb3, 0xe0, 0xfd, 0x15, 0xf9, 0x99, 0x20, 0x21,
	0x8b, 0x58, 0xac, 0xd0, 0x97, 0xb0, 0x61, 0xd2, 0x8a, 0x35, 0x72, 0xee, 0x52, 0x2d, 0x34, 0xf3,
	0x64, 0xf4, 0x21, 0x34, 0xfe, 0xc3, 0x59, 0x3d, 0xb8, 0x75, 0x84, 0x3e, 0x85, 0x1d, 0x95, 0x90,
	0x38, 0x25, 0xa1, 0xe2, 0x32, 0xc6, 0x3c, 0xa6, 0xec, 0x65, 0xb1, 0x3d, 0x76, 0x89, 0x70, 0x35,
	0xde, 0xfd, 0xbb, 0x0a, 0x1b, 0xa6, 0x0c, 0xfa, 0x1a, 0x6a, 0x6f, 0x9c, 0x16, 0x2d, 0xfd, 0xbf,
	0xd1, 0xcd, 0xc2, 0x28, 0xfa, 0x1c, 0xaa, 0x29, 0xa7, 0xcc, 0xb4, 0xb3, 0xbd, 0xbf, 0x77, 0xd7,
	0x83, 0x7d, 0x9f, 0x53, 0xe6, 0x99, 0x54, 0xd4, 0x82, 0xda, 0x4f, 0x19, 0x89, 0x55, 0x16, 0xe5,
	0xbb, 0x5d, 0xf5, 0x96, 0xb1, 0xe6, 0xd2, 0x2c, 0x50, 0x3c, 0xbc, 0x48, 0xcd, 0x56, 0x57, 0xbd,
	0x65, 0x8c, 0x9e, 0xc0, 0xf6, 0x42, 0x4a, 0x8a, 0x15, 0x17, 0xf9, 0x25, 0x3b, 0x1b, 0xda, 0xdb,
	0x51, 0xc5, 0x6b, 0x68, 0xfc, 0x84, 0x8b, 0x7c, 0xb5, 0x07, 0x70, 0x7f, 0x35, 0x0f, 0x2b, 0x1e,
	0x31, 0xe7, 0x9e, 0x7e, 0xcb, 0x8e, 0x2a, 0x9e, 0x5d, 0x4e, 0xd6, 0x97, 0x8e, 0x8e, 0xa0, 0xa9,
	0x33, 0x30, 0x8f, 0xf1, 0x5c, 0x26, 0x21, 0x73, 0x36, 0x8d, 0x99, 0x8f, 0xee, 0x34, 0xa3, 0x9f,
	0x72, 0xe3, 0xb1, 0xce, 0xf5, 0xea, 0xea, 0x36, 0xd0, 0x8b, 0x9a, 0x30, 0x9a, 0x85, 0x0c, 0xcb,
	0x58, 0x5c, 0x39, 0xb5, 0x8e, 0xd5, 0xab, 0x79, 0x90, 0x43, 0xd3, 0x58, 0x5c, 0xa1, 0x8f, 0xe1,
	0xbd, 0xe2, 0xbd, 0x8f, 0x98, 0x22, 0x94, 0x28, 0xe2, 0x6c, 0x99, 0x0b, 0xda, 0xce, 0xe1, 0x67,
	0x05, 0xda, 0xfd, 0x0a, 0xaa, 0x7a, 0x64, 0xe8, 0x01, 0xd8, 0xbe, 0x7b, 0x38, 0xc2, 0xcf, 0x8f,
	0xfd, 0xd9, 0xe8, 0xc0, 0x1d, 0xbb, 0xa3, 0x43, 0xbb, 0x82, 0x1a, 0x50, 0x33, 0xe8, 0xf0, 0xf9,
	0x99, 0x6d, 0xa1, 0x26, 0x6c, 0x99, 0xc8, 0x1f, 0x4d, 0x26, 0xf6, 0x5a, 0xf7, 0x17, 0x0b, 0xea,
	0xa5, 0x0e, 0xd1, 0x1e, 0x3c, 0x3a, 0x71, 0x9f, 0x8d, 0xb0, 0x7b, 0x8c, 0xc7, 0x53, 0xef, 0xe0,
	0xdf, 0x5a, 0x0f, 0x61, 0x67, 0x95, 0x76, 0xa7, 0x07, 0xb6, 0x85, 0x76, 0xe1, 0x83, 0x55, 0x78,
	0x36, 0xf5, 0x4f, 0xf0, 0xf4, 0x78, 0x72, 0x66, 0xaf, 0xa1, 0x36, 0xb4, 0x56, 0xc9, 0xb1, 0x3b,
	0x99, 0xe0, 0xa9, 0x87, 0x9f, 0xba, 0x93, 0x89, 0xbd, 0x3e, 0xb4, 0x4b, 0x57, 0x25, 0x63, 0x26,
	0xe7, 0xc3, 0xd3, 0x57, 0xd7, 0x6d, 0xeb, 0xf5, 0x75, 0xdb, 0xfa, 0xeb, 0xba, 0x6d, 0xfd, 0x7a,
	0xd3, 0xae, 0xbc, 0xbe, 0x69, 0x57, 0xfe, 0xb8, 0x69, 0x57, 0x5e, 0x7c, 0xb3, 0xe0, 0xea, 0x3c,
	0x0b, 0xfa, 0xa1, 0x8c, 0x06, 0x4f, 0xcf, 0x4e, 0x47, 0xc7, 0x4c, 0xfd, 0x2c, 0x93, 0x8b, 0x81,
	0x1e, 0xfe, 0x67, 0xcb, 0x8f, 0x75, 0xfe, 0x2d, 0x7f, 0xeb, 0x3f, 0x10, 0xdc, 0x33, 0xc4, 0x17,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x74, 0xde, 0xcc, 0x23, 0x06, 0x00, 0x00,
}

func (m *OrderId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClobPairId != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.ClobPairId))
		i--
		dAtA[i] = 0x20
	}
	if m.OrderFlags != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.OrderFlags))
		i--
		dAtA[i] = 0x18
	}
	if m.ClientId != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.ClientId))
		i--
		dAtA[i] = 0x15
	}
	{
		size, err := m.SubaccountId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *OrdersFilledDuringLatestBlock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrdersFilledDuringLatestBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrdersFilledDuringLatestBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for iNdEx := len(m.OrderIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOrder(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *PotentiallyPrunableOrders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PotentiallyPrunableOrders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PotentiallyPrunableOrders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for iNdEx := len(m.OrderIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOrder(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *OrderFillState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderFillState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderFillState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PrunableBlockHeight != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.PrunableBlockHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.FillAmount != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.FillAmount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StatefulOrderTimeSliceValue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatefulOrderTimeSliceValue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatefulOrderTimeSliceValue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for iNdEx := len(m.OrderIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrderIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOrder(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StatefulOrderPlacement) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StatefulOrderPlacement) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StatefulOrderPlacement) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TransactionIndex != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.TransactionIndex))
		i--
		dAtA[i] = 0x18
	}
	if m.BlockHeight != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.Order.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Order) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Order) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ClientMetadata != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.ClientMetadata))
		i--
		dAtA[i] = 0x48
	}
	if m.ReduceOnly {
		i--
		if m.ReduceOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.TimeInForce != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.TimeInForce))
		i--
		dAtA[i] = 0x38
	}
	if m.GoodTilOneof != nil {
		{
			size := m.GoodTilOneof.Size()
			i -= size
			if _, err := m.GoodTilOneof.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.Subticks != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.Subticks))
		i--
		dAtA[i] = 0x20
	}
	if m.Quantums != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.Quantums))
		i--
		dAtA[i] = 0x18
	}
	if m.Side != 0 {
		i = encodeVarintOrder(dAtA, i, uint64(m.Side))
		i--
		dAtA[i] = 0x10
	}
	{
		size, err := m.OrderId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Order_GoodTilBlock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order_GoodTilBlock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOrder(dAtA, i, uint64(m.GoodTilBlock))
	i--
	dAtA[i] = 0x28
	return len(dAtA) - i, nil
}
func (m *Order_GoodTilBlockTime) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Order_GoodTilBlockTime) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.GoodTilBlockTime))
	i--
	dAtA[i] = 0x35
	return len(dAtA) - i, nil
}
func encodeVarintOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OrderId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.SubaccountId.Size()
	n += 1 + l + sovOrder(uint64(l))
	if m.ClientId != 0 {
		n += 5
	}
	if m.OrderFlags != 0 {
		n += 1 + sovOrder(uint64(m.OrderFlags))
	}
	if m.ClobPairId != 0 {
		n += 1 + sovOrder(uint64(m.ClobPairId))
	}
	return n
}

func (m *OrdersFilledDuringLatestBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for _, e := range m.OrderIds {
			l = e.Size()
			n += 1 + l + sovOrder(uint64(l))
		}
	}
	return n
}

func (m *PotentiallyPrunableOrders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for _, e := range m.OrderIds {
			l = e.Size()
			n += 1 + l + sovOrder(uint64(l))
		}
	}
	return n
}

func (m *OrderFillState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FillAmount != 0 {
		n += 1 + sovOrder(uint64(m.FillAmount))
	}
	if m.PrunableBlockHeight != 0 {
		n += 1 + sovOrder(uint64(m.PrunableBlockHeight))
	}
	return n
}

func (m *StatefulOrderTimeSliceValue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OrderIds) > 0 {
		for _, e := range m.OrderIds {
			l = e.Size()
			n += 1 + l + sovOrder(uint64(l))
		}
	}
	return n
}

func (m *StatefulOrderPlacement) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Order.Size()
	n += 1 + l + sovOrder(uint64(l))
	if m.BlockHeight != 0 {
		n += 1 + sovOrder(uint64(m.BlockHeight))
	}
	if m.TransactionIndex != 0 {
		n += 1 + sovOrder(uint64(m.TransactionIndex))
	}
	return n
}

func (m *Order) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OrderId.Size()
	n += 1 + l + sovOrder(uint64(l))
	if m.Side != 0 {
		n += 1 + sovOrder(uint64(m.Side))
	}
	if m.Quantums != 0 {
		n += 1 + sovOrder(uint64(m.Quantums))
	}
	if m.Subticks != 0 {
		n += 1 + sovOrder(uint64(m.Subticks))
	}
	if m.GoodTilOneof != nil {
		n += m.GoodTilOneof.Size()
	}
	if m.TimeInForce != 0 {
		n += 1 + sovOrder(uint64(m.TimeInForce))
	}
	if m.ReduceOnly {
		n += 2
	}
	if m.ClientMetadata != 0 {
		n += 1 + sovOrder(uint64(m.ClientMetadata))
	}
	return n
}

func (m *Order_GoodTilBlock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovOrder(uint64(m.GoodTilBlock))
	return n
}
func (m *Order_GoodTilBlockTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}

func sovOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOrder(x uint64) (n int) {
	return sovOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OrderId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaccountId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SubaccountId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			m.ClientId = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderFlags", wireType)
			}
			m.OrderFlags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderFlags |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClobPairId", wireType)
			}
			m.ClobPairId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClobPairId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrdersFilledDuringLatestBlock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrdersFilledDuringLatestBlock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrdersFilledDuringLatestBlock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderIds = append(m.OrderIds, OrderId{})
			if err := m.OrderIds[len(m.OrderIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PotentiallyPrunableOrders) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PotentiallyPrunableOrders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PotentiallyPrunableOrders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderIds = append(m.OrderIds, OrderId{})
			if err := m.OrderIds[len(m.OrderIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderFillState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderFillState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderFillState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillAmount", wireType)
			}
			m.FillAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FillAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrunableBlockHeight", wireType)
			}
			m.PrunableBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrunableBlockHeight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatefulOrderTimeSliceValue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatefulOrderTimeSliceValue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatefulOrderTimeSliceValue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderIds = append(m.OrderIds, OrderId{})
			if err := m.OrderIds[len(m.OrderIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StatefulOrderPlacement) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StatefulOrderPlacement: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StatefulOrderPlacement: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Order.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionIndex", wireType)
			}
			m.TransactionIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TransactionIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Order) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Order: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Order: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			m.Side = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Side |= Order_Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantums", wireType)
			}
			m.Quantums = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantums |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subticks", wireType)
			}
			m.Subticks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Subticks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoodTilBlock", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GoodTilOneof = &Order_GoodTilBlock{v}
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoodTilBlockTime", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.GoodTilOneof = &Order_GoodTilBlockTime{v}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeInForce", wireType)
			}
			m.TimeInForce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeInForce |= Order_TimeInForce(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReduceOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ReduceOnly = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientMetadata", wireType)
			}
			m.ClientMetadata = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClientMetadata |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOrder = fmt.Errorf("proto: unexpected end of group")
)
