syntax = "proto3";
package dydxcometbft.types;

option go_package = "github.com/KYVENetwork/dydx-cometbft/proto/dydxcometbft/types";

import "gogoproto/gogo.proto";
import "dydxcometbft/types/types.proto";
import "dydxcometbft/types/evidence.proto";

message Block {
  Header                        header      = 1 [(gogoproto.nullable) = false];
  Data                          data        = 2 [(gogoproto.nullable) = false];
  dydxcometbft.types.EvidenceList evidence    = 3 [(gogoproto.nullable) = false];
  Commit                        last_commit = 4;
}
